### ISSUE TITLE
Cannot install luarocks 2.4.x

### ISSUE THREAD

**Issue by waruqi** [leafo/gh-actions-luarocks#8]
It works fine when installing luarocks 3.x, but cannot install luarocks 2.x

```
      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: 2.4.3
```

```console
/bin/tar xz --warning=no-unknown-keyword -C .install -f /home/runner/work/_temp/d4cf169e-ed6e-4081-a089-0be2837739e3
/home/runner/work/luarocks-build-xmake/luarocks-build-xmake/.install/luarocks-2.4.3/configure --with-lua-bin=/home/runner/work/luarocks-build-xmake/luarocks-build-xmake/.lua/bin --prefix=/home/runner/work/luarocks-build-xmake/luarocks-build-xmake/.luarocks
Lua interpreter not found in /home/runner/work/luarocks-build-xmake/luarocks-build-xmake/.lua/bin
You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help.

configure failed.
```

https://github.com/xmake-io/luarocks-build-xmake/runs/1715427126?check_suite_focus=true
